---
title: "inferencia_wikimidia"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
theme_set(theme_bw())

library(broom)
```

```{r}
dados <- read_csv(here::here("data/search_data.csv"))
```

1. A diferença entre o clickthrough rate dos grupos A e B; e
2. A diferença na proporção buscas com zero resultados nos grupos A e B

```{r}
ctr_values <- dados %>% group_by(group) %>% summarise(CTR = mean(num_clicks))

ctr_values
```

```{r}
library(perm)

ctr_A = dados %>% filter(group == 'a') %>% pull(num_clicks)
ctr_B = dados %>% filter(group == 'b') %>% pull(num_clicks)

permTS(ctr_A, ctr_B)
```


```{r}
theta_diferenca = function(df, i){
    ctrs = df %>% 
        slice(i) %>% 
        group_by(group) %>% 
        summarise(ctr = mean(num_clicks)) 
    
    ctr_a = ctrs %>% filter(group == "a") %>% pull(ctr)
    ctr_b = ctrs %>% filter(group == "b") %>% pull(ctr)
    
    ctr_a - ctr_b
}
```

```{r}
library(boot)
dados %>% 
    boot(statistic = theta_diferenca, R = 4000) %>% 
    tidy(conf.level = 0.95, 
         conf.int = TRUE)
```


```{r}
dados <- dados %>% mutate(is_zero = results == 0)

```

```{r}
a = dados %>% group_by(group) %>% summarise(prop_zero = sum(is_zero)/n()) %>% filter(group == 'a') %>% pull(prop_zero)
b = dados %>% group_by(group) %>% summarise(prop_zero = sum(is_zero)/n()) %>% filter(group == 'b') %>% pull(prop_zero)

theta_diff_prop = a - b
```

```{r}

```

```{r}
prop_diff = function(d){
    proporcoes = d %>% 
        mutate(grupo_embaralhado = sample(group, n())) %>% 
        group_by(grupo_embaralhado) %>% 
        summarise(prop_zero = sum(is_zero)/n()) 
    
    prop_a = proporcoes %>% filter(grupo_embaralhado == "a") %>% pull(prop_zero)
    prop_b = proporcoes %>% filter(grupo_embaralhado == "b") %>% pull(prop_zero)
    
    prop_a - prop_b
}
```


```{r}
diffs1 = replicate(5000, {prop_diff(dados)})

tibble(diferenca = diffs1) %>% 
  ggplot(aes(x = diferenca)) + 
  # geom_histogram(binwidth = .2, fill = "white", color = "darkgreen") + 
    geom_density(fill = "white", color = "darkgreen") + 
  geom_vline(xintercept = theta_diff_prop, 
             color = "orange") + 
    geom_vline(xintercept = - theta_diff_prop, 
             color = "orange") + 
    geom_rug()
```

```{r}
mean(abs(diffs1) >= abs(theta_diff_prop))
```

